# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{httpdoc}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Staubo"]
  s.date = %q{2011-02-23}
  s.default_executable = %q{httpdoc}
  s.description = %q{Simple documentation generator for publishing APIs from Rails applications.}
  s.email = %q{alex@bengler.no}
  s.executables = ["httpdoc"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "LICENSE",
    "README.markdown",
    "VERSION",
    "lib/httpdoc.rb",
    "lib/httpdoc/generator.rb",
    "lib/httpdoc/model.rb",
    "lib/httpdoc/parser.rb",
    "lib/httpdoc/rendering.rb"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://github.com/origo/httpdoc}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple documentation generator for publishing APIs from Rails applications.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
    else
      s.add_dependency(%q<RedCloth>, [">= 0"])
    end
  else
    s.add_dependency(%q<RedCloth>, [">= 0"])
  end
end

